site_name: CIP - miniBRS
repo_url: https://github.com/Cloud-Innovation-Partners/miniBRS
site_description: mini-BRS is a tool that provides ServiceNow SalesForce data backup facility via programmatic workflows scheduled and monitored by Apache Airflow
site_author: Cloud Innovation Partners

nav:
  - User Guide: index.md
  - First Steps:
    - Installation: installation.md
    - Upgrade: upgrade.md
  - Getting Started:
    - Settings: settings.md
    - How It Works: how_it_works.md
  - Advanced Features:
    - Hooks & Operators: hooks_and_operators.md
    - Recovery & Logs: logs.md
  - References:
      - Generate DropBox access_token: dropbox.md
      - Installing Database Other than SQLite for Airflow: https://airflow.apache.org/docs/stable/installation.html#initiating-airflow-database
      - Installing Airflow as a Service: https://medium.com/@shahbaz.ali03/run-apache-airflow-as-a-service-on-ubuntu-18-04-server-b637c03f4722
  - About:
    - Who Maintains miniBRS: about.md
    - License: LICENSE.md

theme:
    name: readthedocs
extra:
    version: 1.0