site_name: CIP - miniBRS
repo_url: https://github.com/Cloud-Innovation-Partners/miniBRS
site_description: mini-BRS is a tool that provides ServiceNow SalesForce data backup facility via programmatic workflows scheduled and monitored by Apache Airflow
site_author: Cloud Innovation Partners

nav:
  - User Guide: index.md
  - First Steps:
    - Installation: installation.md
    - Upgrade: upgrade.md
  - Getting Started:
    - Settings: settings.md
    - How It Works: how_it_works.md
  - Advanced Features:
    - Hooks & Operators: hooks_and_operators.md
    - Recovery & Logs: logs.md
  - About:
    - Who Maintains miniBRS: about.md
    - License: LICENSE.md

theme:
    name: readthedocs
extra:
    version: 1.0